version: '3.7'

networks:
  host:

services:
  condat-postgres:
    hostname: console-data-cray-console-data-postgres
    image: dtr.dev.cray.com/library/postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=console
      - POSTGRES_USER=console
      - POSTGRES_DB=console
    networks:
      - host
    healthcheck:
      test: ["CMD", "psql", "-U", "console"]
      interval: 5s
      timeout: 5s
      retries: 5
  cray-console-data:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=condat-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=console
      - POSTGRES_USER=console
      - POSTGRES_PASSWD=console
    hostname: cray-console-data
    depends_on:
      condat-postgres:
        condition: service_healthy
    networks:
      - host
