apiVersion: v2
name: cray-console-data
version: 0.0.0
description: Kubernetes resources for console-data
keywords:
  - cray-console
  - cray-console-data
home: https://github.com/Cray-HPE/console-data
sources:
  - "https://github.com/Cray-HPE/console-data"
dependencies:
  - name: cray-service
    version: ^7.0.0
    repository: "https://artifactory.algol60.net/artifactory/csm-helm-charts/"
maintainers:
  - name: dlaine-hpe
    email: laine@hpe.com
appVersion: 0.0.0
annotations:
  artifacthub.io/images: |
    - name: cray-console-data
      image: artifactory.algol60.net/csm-docker/stable/cray-console-data:0.0.0
  artifacthub.io/license: MIT
