apiVersion: v1
description: Console Data
name: cray-console-data
home: "scms/console-data"
# The version string is replaced at build time by the build prep script
version: @VERSION@
description: "Kubernetes resources for console-data"
keywords:
  - cray-console-data
sources:
  - "https://github.com/Cray-HPE/console-data"
maintainers:
  - name: rnoska
    email: rnoska@hpe.com
