# Please refer to https://github.com/Cray-HPE/base-charts/tree/master/kubernetes/cray-service/values.yaml
# for more info on values you can set/override
# Note that cray-service.containers[*].image and cray-service.initContainers[*].image map values are one of the only structures that
# differ from the standard kubernetes container spec:
# image:
#   repository: ""
#   tag: "" (default = "latest")
#   pullPolicy: "" (default = "IfNotPresent")

cray-service:
  type: Deployment
  nameOverride: cray-console-data
  containers:
    cray-console-data:
      name: console-data
      image:
        repository: artifactory.algol60.net/csm-docker/stable/cray-console-data
        # tag defaults to chart appVersion
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: "4"
          memory: 4Gi
        requests:
          cpu: 100m
          memory: 64Mi
      livenessProbe:
        httpGet:
          port: 80
          path: /liveness
        initialDelaySeconds: 5
        periodSeconds: 60
      readinessProbe:
        httpGet:
          port: 80
          path: /readiness
        initialDelaySeconds: 10
        periodSeconds: 60
      env:
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: console.cray-console-data-postgres.credentials
            key: username
      - name: POSTGRES_PASSWD
        valueFrom:
          secretKeyRef:
            name: console.cray-console-data-postgres.credentials
            key: password

  sqlCluster:
    enabled: true
    instanceCount: 3
    postgresVersion: "11"
    volumeSize: 2Gi
    users:
      console: []
    databases:
      service_db: console

  ingress:
    enabled: true
    prefix: /apis/consoledata
    uri: " "
  strategy:
    type: Recreate
